version: 2
jobs:
  build:
    docker:
      - image: $DOCKER_USERNAME/katex-fonts:29d4cdbc

    steps:
      - checkout

      - run:
          name: Build fonts
          command: |
            cd src
            cp default.cfg custom.cfg
            make custom.cfg.pl
            make -C fonts/OTF/TeX ttf woff woff2
            cd ..
            rm -f fonts/*.*
            cp src/fonts/OTF/TeX/ttf/*.ttf fonts
            cp src/fonts/OTF/TeX/woff/*.woff fonts
            cp src/fonts/OTF/TeX/woff2/*.woff2 fonts
            tar zcf fonts.tar.gz fonts

      - run:
          name: Build metrics
          command: ./buildMetrics.sh

      - store_artifacts:
          path: fonts.tar.gz
          destination: fonts.tar.gz

      - store_artifacts:
          path: fontMetricsData.js
          destination: fontMetricsData.js
